

title: Wallace Maxters
logo: /assets/img/logo.svg#default
white_logo: /assets/img/logo.svg#white
email: wallacemaxters@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Um blog com dicas, tutoriais e informações sobre programação e desenvolvimento web
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wallacemaxters.com.br" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: wallacemaxters
github_username:  wallacemaxters

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

github: https://github.com/wallacemaxters
stackoverflow: https://pt.stackoverflow.com/users/4995/wallace-maxters
facebook: https://www.facebook.com/wallace.maxters.7

permalink: /blog/:year/:month/:day/:title

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


safe: false

future: false

locale: pt-br

collections:
  categorias:
    output: true
    permalink: /:collection/:name
  ferramentas:
    output: true
    permalink: /:collection/:name



# author: wallacemaxters